// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DongTrungHieu261.Migrations
{
    [DbContext(typeof(LTQLDB))]
    [Migration("20240106071925_SinhVien")]
    partial class SinhVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("DongTrungHieu261.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoSinhVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLop")
                        .HasColumnType("TEXT");

                    b.HasKey("MaLop");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("DongTrungHieu261.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaLop")
                        .HasColumnType("TEXT");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("DongTrungHieu261.Models.SinhVien", b =>
                {
                    b.HasOne("DongTrungHieu261.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop");

                    b.Navigation("LopHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
